---
title: "day220624"
output: 
  html_document:    
        keep_md: true
date: '2022-06-24'
---



## 복습
- 통계 검정
  + 평균 차이 검정 : 수치데이터 + 번주 데이터(두 그룹)
    - 중급 이상 : 세 그룹 이상
  + 비율 차이 검정 : 번주 데이터
  + 상관 관계 : 수치 데이터
  + 회귀 
  
  + 분석을 위한 데이터가 적절한지 검정
  + 등분산 검정, 수치 데이터가 정규분포를 이루는가(정규성 검정)
  +
  
- 귀무가설, 대립가설 적절하게 설정
 + 서울의 평균 임금과 부산의 평균 임금에 차이가 있을 것이다. 
 + 선행연구(논문 찾아서)
 
- 테스트 
 + t.test, chisq.test, cor.test
 + p.value
  - p.value > 0.05 --> 귀무가설 지지
  - p.value < 0.05 --> 대립가설 지지

## 회귀의 중요성
- 기초통계 : 특정한 결과에 영향을 주는 주 요인이 뭐냐? 이걸 찾는 회귀
- 회귀분석과 종류
 + 1세대 회귀 방법론 : 다항회귀분석, 다중회귀분석, 포아송회귀분석, etc
 + 2세대 회귀 방법론 : 구조방정식
 
- 귀무가설 & 대립가설 존재
 + 귀무가설 : x(=독립변수)가 y(=종속변수)에 영향을 주지 않는다.
 + 대립가설 : x가 y에 영향을 준다.
 
- lm(종속변수 ~ 독립변수, data)
 + p.value

```r
 RA <- lm(data=mtcars, mpg~disp)
 summary(RA) 
```

```
## 
## Call:
## lm(formula = mpg ~ disp, data = mtcars)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4.8922 -2.2022 -0.9631  1.6272  7.2305 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(>|t|)    
## (Intercept) 29.599855   1.229720  24.070  < 2e-16 ***
## disp        -0.041215   0.004712  -8.747 9.38e-10 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 3.251 on 30 degrees of freedom
## Multiple R-squared:  0.7183,	Adjusted R-squared:  0.709 
## F-statistic: 76.51 on 1 and 30 DF,  p-value: 9.38e-10
```
 - p-value : 0.05보다 크면 문제가 있다는 것을 나타낸다.
 - (Intercept) = 기울기
 - 전진소거법, 후진소거법
  + y = disp + var1
  + y = disp + var1 + var2 
  + y = disp + var1 + var2 +var3
 - 위 y값 중 제일 좋은 값을 선택하여 비교분석해야된다.
 y(mpg) = 29.599855 - 0.041215
 
 
 
 
- 머신러닝, 인공지능
 + 주 목적은 예측
 + y = ax + b
 
-

Residual standard error: 3.251 on 30 degrees of freedom
Multiple R-squared (결정계수=설명력):  0.7183,	Adjusted R-squared:  0.709 

R-squared (결정계수=설명력) : 0~1
 - 1로 가까워질수록 설명력이 좋다.
 - 0.7183에 나머지 0.3817의 요인을 찾아야된다. 
 - 
 
4)회귀분석
(1)단순회귀분석 : 독립변수가 1개, 종속변수가 1개일 때 함
- 방법1 : lm(data = 데이터세트, 종석변수 ~ 독립변수)
- 방법2 : lm(종석변수 ~ 독립변수, data = 데이터세트)
- 방법3 : lm(데이터세트$종석변수 ~ 데이터세트$독립변수)

- 귀무가설(H0): disp(배기량) 는 mpg(1개런당 주행마일)에 영향을 주지 않는다.
- 대립가설(H1): disp는 mpg에 영향을 준다.

```r
lm(data=mtcars, mpg~disp)
```

```
## 
## Call:
## lm(formula = mpg ~ disp, data = mtcars)
## 
## Coefficients:
## (Intercept)         disp  
##    29.59985     -0.04122
```
 + disp의 계수(Coefficients)는 -0.04122이며, 절편은 29.59985

```r
RA <- lm(data=mtcars, mpg~disp) # 회귀분석 결과를 RA에

summary(RA) #상세 분석결과
```

```
## 
## Call:
## lm(formula = mpg ~ disp, data = mtcars)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4.8922 -2.2022 -0.9631  1.6272  7.2305 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(>|t|)    
## (Intercept) 29.599855   1.229720  24.070  < 2e-16 ***
## disp        -0.041215   0.004712  -8.747 9.38e-10 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 3.251 on 30 degrees of freedom
## Multiple R-squared:  0.7183,	Adjusted R-squared:  0.709 
## F-statistic: 76.51 on 1 and 30 DF,  p-value: 9.38e-10
```
 - 분석결과
  + 회귀모형은 유의수준 p< .001에서 적합하며, 회귀식의 수정된 결정계수 (R^2)는 .709이다. 배기량이 연비에 미치는 회귀계수는 유의수준 p<.001에서 -0.04이다.

  
  
